typography_spectrum: 0.6812682275194675
color:
  brandStrength: 0.37362026888877153
  lightness: 0.4018748365342617
  saturation: 0.8320099054835737
  rhythmicContrast: 0.0837654008064419
  brandColors:
    - '#B7C9DF'
    - '#010506'
    - '#018EC3'
    - '#A7816C'
    - '#00547F'
layout_spectrum: 0.9852233431302011
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1c5c75ce-0720-4549-aa32-48a9f80b9e60.png
name: Nathaliet
navigation:
  - name: Poleras
    url: 'https://thegrid.ai/nathaliet-poleras/'
    type: external
  - name: Crop Tops
    url: 'https://thegrid.ai/nathaliet-croptops'
    type: external
  - name: Blazers
    url: 'https://thegrid.ai/nathaliet-blazers'
    type: external
  - name: Vestidos
    url: 'https://thegrid.ai/nathaliet-vestidos'
    type: external
  - name: Acerca de Nathaliet
    id: cf4e0190-ed87-4feb-a4ab-ae786d0922be
    type: content
  - name: Trajes de Baño
    url: 'https://thegrid.ai/nathaliet-trajes-de-bano/'
    type: external
title: Nathaliet
description: Diseños Exclusivos
