typography_spectrum: 0.4415736007504165
color:
  brandStrength: 0.32077818526886404
  lightness: 0.6093443906866014
  saturation: 0.294144235085696
  rhythmicContrast: 0.5781292377505451
  brandColors:
    - '#FFF8E3'
    - '#CCCC9F'
    - '#33332D'
    - '#9FB4CC'
    - '#DB4105'
layout_spectrum: 0.05426179012283683
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1c5c75ce-0720-4549-aa32-48a9f80b9e60.png
name: Nathaliet
navigation:
  - name: Poleras
    url: 'https://thegrid.ai/nathaliet-poleras/'
    type: external
  - name: Crop Tops
    url: 'https://thegrid.ai/nathaliet-croptops'
    type: external
  - name: Blazers
    url: 'https://thegrid.ai/nathaliet-blazers'
    type: external
  - name: Vestidos
    url: 'https://thegrid.ai/nathaliet-vestidos'
    type: external
  - name: Trajes de Baño
    url: 'https://thegrid.ai/nathaliet-trajes-de-bano/'
    type: external
  - name: '#NathalietMe'
    url: 'https://thegrid.ai/nathalietme/'
    type: external
  - name: Acerca de Nathaliet
    id: cf4e0190-ed87-4feb-a4ab-ae786d0922be
    type: content
title: Nathaliet
description: Diseños Exclusivos
