typography_spectrum: 0.27386314468458295
color:
  brandStrength: 0.7471848907880485
  lightness: 0.6788913754280657
  saturation: 0.39003553055226803
  rhythmicContrast: 0.4260049615986645
  brandColors:
    - '#FFF8E3'
    - '#CCCC9F'
    - '#33332D'
    - '#9FB4CC'
    - '#DB4105'
layout_spectrum: 0.9852233431302011
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/81d5a261-1653-4045-b793-ce186e313239.png
name: Nathaliet
navigation:
  - name: Home
    url: 'http://thegrid.ai/nathaliet/'
    type: external
  - name: Crop Tops
    url: 'https://thegrid.ai/nathaliet-croptops'
    type: external
  - name: Blazers
    url: 'https://thegrid.ai/nathaliet-blazers'
    type: external
  - name: Vestidos
    url: 'https://thegrid.ai/nathaliet-vestidos'
    type: external
  - name: Trajes de Baño
    url: 'https://thegrid.ai/nathaliet-trajes-de-bano/'
    type: external
  - name: '#NathalietMe'
    url: 'https://thegrid.ai/nathalietme/'
    type: external
  - name: Agendar una Cita
    url: 'http://m.me/nathalietme'
    type: external
  - name: Acerca de Nathaliet
    id: cf4e0190-ed87-4feb-a4ab-ae786d0922be
    type: content
  - name: Poleras
    url: 'https://thegrid.ai/nathaliet-poleras/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/61a924bc-090e-46bf-bb9f-a1816980e200.png
title: Nathaliet
description: Diseños Exclusivos
